# Generated by Django 5.2.3 on 2025-06-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_question_option_quiz_question_quiz_submission_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="marks_awarded",
            field=models.FloatField(default=0),
        ),
    ]
